#!/bin/sh
# Bootstrap entrypoint for semgrep-network-broker.
#
# When SCM_TYPE is set, this script regenerates a WireGuard keypair, writes a
# minimal config.yaml + pubkey.txt to ${CONFIG_DIR}, prints the public key for
# registration with Semgrep, then execs the broker with the passed args.
#
# When SCM_TYPE is unset, the script is a pass-through to the broker binary —
# preserving the original ENTRYPOINT behavior for genkey/pubkey/relay/dump and
# normal `-c ... -d ...` invocations.

set -eu

BROKER_BIN="${BROKER_BIN:-/usr/bin/semgrep-network-broker}"
CONFIG_DIR="${CONFIG_DIR:-/emt}"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"
PUBKEY_FILE="${CONFIG_DIR}/pubkey.txt"

if [ -n "${SCM_TYPE:-}" ]; then
    if [ -z "${SCM_BASE_URL:-}" ]; then
        echo "bootstrap: SCM_BASE_URL must be set when SCM_TYPE is set" >&2
        exit 1
    fi

    case "${SCM_TYPE}" in
        github|gitlab|bitbucket|azuredevops) ;;
        *)
            echo "bootstrap: SCM_TYPE must be one of: github, gitlab, bitbucket, azuredevops (got: '${SCM_TYPE}')" >&2
            exit 1
            ;;
    esac

    if [ ! -d "${CONFIG_DIR}" ]; then
        echo "bootstrap: ${CONFIG_DIR} does not exist — mount your config directory, e.g. -v /opt/semgrep-broker:${CONFIG_DIR}" >&2
        exit 1
    fi

    # SCM_BASE_URL is the host base (e.g., https://gitlab.example.com).
    # Strip trailing slash, then append the per-SCM API path for the SCM block.
    # The original host base is reused as the broad allowlist pattern.
    BASE_URL="${SCM_BASE_URL%/}"

    case "${SCM_TYPE}" in
        github)      API_URL="${BASE_URL}/api/v3" ;;
        gitlab)      API_URL="${BASE_URL}/api/v4" ;;
        bitbucket)   API_URL="${BASE_URL}/rest/api/latest" ;;
        azuredevops) API_URL="${BASE_URL}" ;; # Azure DevOps URL shape varies; pass through as-is.
    esac

    if [ -f "${CONFIG_FILE}" ]; then
        echo "bootstrap: ${CONFIG_FILE} already exists — reusing it. Delete the file to force regeneration." >&2
    else
        if [ ! -w "${CONFIG_DIR}" ]; then
            echo "bootstrap: ${CONFIG_DIR} is not writable by UID $(id -u). chown the host directory to that UID, or run the container with --user." >&2
            exit 1
        fi

        PRIVATE_KEY="$("${BROKER_BIN}" genkey)"
        PUBLIC_KEY="$(printf '%s' "${PRIVATE_KEY}" | "${BROKER_BIN}" pubkey)"

        umask 077
        cat > "${CONFIG_FILE}" <<YAML
# Generated by semgrep-network-broker bootstrap on $(date -u +%FT%TZ).
# Contains a WireGuard private key — do not commit or share.
inbound:
  wireguard:
    privateKey: ${PRIVATE_KEY}
  ${SCM_TYPE}:
    baseUrl: ${API_URL}
    allowCodeAccess: true
  allowlist:
    # Broad start: any path under the SCM host, all common methods. Tighten
    # later by replacing this block with specific URL patterns (see README).
    - url: "${BASE_URL}/*"
      methods: [GET, POST, PUT, PATCH, DELETE]
YAML

        cat > "${PUBKEY_FILE}" <<PUBKEY
# Semgrep Network Broker — public key registration
#
# 1. Open https://semgrep.dev and go to your org's Network Broker settings.
# 2. Paste the public key below into the registration form.
# 3. The broker will start picking up heartbeats within ~60s of registration —
#    no container restart needed.
#
# Generated: $(date -u +%FT%TZ)

${PUBLIC_KEY}
PUBKEY

        BANNER_TEXT="
================================================================================
  Semgrep Network Broker — REGISTER THIS PUBLIC KEY at https://semgrep.dev
--------------------------------------------------------------------------------
  ${PUBLIC_KEY}
--------------------------------------------------------------------------------
  Also saved to:  ${PUBKEY_FILE}
  Config:         ${CONFIG_FILE}

  Steps:
    1. Open https://semgrep.dev and navigate to your org's Network Broker
       settings (under SCM / integrations).
    2. Paste the public key above into the registration form.
    3. The broker is already running and retrying heartbeats. Within ~60s of
       registration, logs will show 'Established connectivity with Semgrep' —
       no restart needed.

  To re-display this banner later:  docker logs <container-name>
  Or just read the file:            cat ${PUBKEY_FILE}

  Bootstrap will NOT regenerate keys on subsequent container starts as long as
  ${CONFIG_FILE} exists. Delete that file if you ever need to rotate.
================================================================================
"
        # Print to both streams so it surfaces regardless of how the container
        # is launched (detached, attached, captured to a logger, etc.).
        printf '%s\n' "${BANNER_TEXT}" >&2
        printf '%s\n' "${BANNER_TEXT}"
    fi
fi

exec "${BROKER_BIN}" "$@"
